<?php $this->headLink()->appendStylesheet('/css/popup.css'); ?>
<?php $this->headLink()->appendStylesheet('/css/fix-style.css'); ?>
<?php $this->headScript()->appendFile($this->basePath() . '/js/ajax-fix.js'); ?>

<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="text-center">Terminarz</h3>	
		<a  class="btn btn-success btn-sm " href="/fixtures/addmany"><span class="glyphicon glyphicon-plus"></span> Dodaj</a>			
	</div>
	<div class="panel-body">	
		<form class="form-horizontal" role="form">
		 	<div class="form-group">
		    	<label for="inputEmail3" class="col-md-3 col-md-offset-3 control-label">Wybierz numer kolejki</label>
			    <div class="col-md-1">
			      <select  class="form-control" id="roundChoose" placeholder="numer">
			      	<?php foreach ($round as $key => $value): ?>
			      		<option value="<?php echo $value->round ?>"><?php echo $value->round ?></option>
			      	<?php endforeach ?>	
			      </select>		      			      	
			    </div>
			    <img class="fix-loader" style="display: none;" src="/img/25.gif"/>
		  	</div>	
	  	</form>		
		<div class="col-md-12">
			<table class="table table-bordered">
				<?php foreach ($fix as $key => $value): ?>
					<tr>
						<td class="text-right col-md-4"><?php echo $value->home_team ?></td>
						<td class="col-md-1 text-center"><?php echo $value->home_team_goals ?></td>
						<td class="col-md-1 text-center">:</td>
						<td class="col-md-1 text-center"><?php echo $value->away_team_goals ?></td>
						<td class="col-md-4"><?php echo $value->away_team ?></td>
					</tr>
				<?php endforeach ?>				
			</table>
		</div>	
	</div>
</div> 
