<?php echo $this->doctype(); ?>
<html lang="pl">
<head>
	<title>CWKS Resovia</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<?php 
	  echo $this->headTitle();
	  echo $this->headScript()->prependFile($this->basePath() . '/js/jquery-1.11.0.min.js')
	  			          			  ->appendFile($this->basePath() . '/js/bootstrap.min.js')
                            ->appendFile($this->basePath() . '/js/ajax.js'); 	 
	  echo $this->headLink()->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
                          ->appendStylesheet($this->basePath() . '/css/main.css');                           
	?>  
</head>
 <body>
   <div class="container">
    <header>
      	<div class="row">
    		  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
            		<div class="navbar-header">              
  	              		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
  		                <span class="sr-only">Toggle navigation</span>
  		                <span class="icon-bar"></span>
  		                <span class="icon-bar"></span>
  		                <span class="icon-bar"></span>
               		 </button>
                    <a class="navbar-brand" href="/admin">Panel administracyjny</a>
            		</div>           
                  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
                    	<?php echo $this->navigation('navigation')
                        ->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(0)
                        ->setUlClass('nav navbar-nav');
                      ?>
                  </div>         
          	</div>
          </div>
      	</div>
    </header>  
    <div class="row">  
      <?php echo $this->layout()->content; ?>
      
    </div>   
 </body>
</html>