<?php $this->headScript()->appendFile($this->basePath() . '/js/ckeditor/ckeditor.js')
                         ->appendFile($this->basePath() . '/js/ckeditor/adapters/jquery.js'); ?>
<?php $this->headScript()->appendFile($this->basePath() . '/js/validation.js')
                         ->appendFile($this->basePath() . '/js/ckfinder.js'); ?>
<?php $this->headScript()->appendFile($this->basePath() . '/uploadify/jquery.uploadify.min.js'); ?>
<?php $this->headLink()->appendStylesheet($this->basePath() . '/uploadify/uploadify.css') ?>
<script>
	$( '.ckeditor' ).ckeditor();
	$(function() {
    	$('#photo').uploadify({
	        'swf'      : '/uploadify.swf',
	        'uploader' : '/posts/uploadifyAjax',
	        'checkExisting' : '/posts/checkExistPhotoAjax',
	        'multi'    : false,
	        'fileTypeExts' : '*.jpg; *.png',
	        'onUploadSuccess' : function(file, data, response) {
	        	$('#photo').hide();
	        	$('#photo-view').append('<img src="/img/posts/' + file.name +'" />');
	        	$('#file').val(file.name);
			}
	    });
	});
</script>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="text-center">Tworzenie newsa</h3>		
	</div>
	<div class="panel-body">
		
		<form action="/posts/add" method="POST" name="post" id="post">
		<?php echo $this->formHidden($form->get('id'));?>
		<?php echo $this->formHidden($form->get('file'));?>
		<div class="form-group">
			<div class="col-md-10 col-md-offset-1">			
				<?php echo $this->formLabel($form->get('name'));?>	
			</div>	
			<div class="col-md-6 col-md-offset-1">
				<?php echo $this->formElement($form->get('name'));?>
			</div>
			<div class="col-md-4 ">
				<div class="alert alert-danger alert-dismissable text-center" id="alert1" style="display: none;" >				  
				  Nazwa nie może być pusta!
				</div>
			</div>
		</div>
		<div class="form-group">
			<div class="col-md-10 col-md-offset-1">			
				<?php echo $this->formLabel($form->get('photo'));?>	
			</div>
			<div class="col-md-6 col-md-offset-1">
				<?php echo $this->formElement($form->get('photo'));?>
			</div>		
			<div class="col-md-10 col-md-offset-1" id="photo-view"></div>					
		</div>		
		<div class="form-group">			
			<div class="col-md-10 col-md-offset-1">
				<?php echo $this->formRow($form->get('content'));?>			
			</div>
		</div>	
		<div class="col-md-10 col-md-offset-1 text-right">				
			<a class="btn btn-danger" href="/posts">Anuluj</a>	
				<?php echo $this->formRow($form->get('submit'));?>						
		</div>
		<?php echo $this->form()->closeTag(); ?>		
	</div>
</div>