<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->

<?php if ($this->pageCount): ?>
<div class="paginationControl">
  <ul class="pagination pagination-sm">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <li ><a href="<?php echo $this->url($this->route, array('page' => $this->previous)); ?>">
    &lt;
  </a></li>
<?php else: ?>
  <li class="disabled"><a>&lt;</a></li>
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <li ><a href="<?php echo $this->url($this->route, array('page' => $page)); ?>">
        <?php echo $page; ?>
    </a> </li>
  <?php else: ?>
    <li class="active"><a><?php echo $page; ?></a></li>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <li><a href="<?php echo $this->url($this->route, array('page' => $this->next)); ?>">
    &gt;
  </a></li>
<?php else: ?>
  <li class="disabled"><a>&gt;</a></li>
<?php endif; ?>
</ul>
</div>
<?php endif; ?>

