<?php $this->headLink()->appendStylesheet('/css/popup.css'); ?>
<div class="col-sm-12">
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="text-center">Strony</h3>	
		<a  class="btn btn-success btn-sm " href="/pages/add"><span class="glyphicon glyphicon-plus"></span> Nowa</a>			
	</div>
	<div class="panel-body">
		<div class="row">
<div class="col-sm-8 col-sm-offset-2">	
	<table class="table table-hover">
		<thead>
	<tr>
		<th>Nazwa</th>	
		<th><div class="text-center">Opcje</div></th>	
	</tr>
	</thead>	
	<?php foreach ($this->pages as $key => $value): ?>	
	<?php $name = str_replace('_', ' ', $value->name); ?>	
		<tr>
			<td><?php echo $name; ?></td>	
			<td>
				<div class="pull-right">					
					<a href='/pages/edit/<?php echo $value->id;?>' class="btn btn-warning btn-xs" ><span class="glyphicon glyphicon-edit"></span> Edycja</a>
					<a href='#popup' data-toggle="modal" data-target="#popup" id='<?php echo $value->id;?>' class="delete-ajax-page btn btn-danger btn-xs" ><span class="glyphicon glyphicon-trash"></span> Usuń</a>	
				</div>	
			</td>		
		</tr>	
	<?php endforeach ?>
	</table>	
</div>

		</div>
	</div>
</div>

 <div class="modal fade in" id="popup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
          <div class="modal-header">
            <a class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span></a>
            <h3 id="modalLabel">Usuwanie</h3>            
          </div> 
          <div class="modal-body">
        	<p>Czy na pewno chcesz usunąć tą strone?</p>
     	 </div>         
            <div class="modal-footer">     	
            		<img id="loader" src="/img/25.gif" style="display:none" class="pull-left"/>	
            		<div class="btn-group">           	
	              	<button class="btn btn-danger " data-dismiss="modal" aria-hidden="true">Nie</button>
	              	<button class="ok-delete-page btn btn-success ">Tak</button>  
              	</div>            
            </div>
          </div>
        </div>
      </div>
      </div>